### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by githubsteve7** [conor-f/spotibar#21]
I am getting the following error when I try to install:

Where should we write this config?
	Filepath: [~/.spotibar_config.json]
Where should we cache your authentication tokens?
	Filepath: [~/.spotibar_auth_cache]
Successfully authenticated.
Traceback (most recent call last):
  File "/usr/local/bin/spotibar", line 33, in <module>
    sys.exit(load_entry_point('spotibar==0.3.11', 'console_scripts', 'spotibar')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/spotibar/client.py", line 437, in main
    sys.exit(0)
    ^^^
NameError: name 'sys' is not defined

Tried multiple times, uninstalled, no luck. Thanks.

**Comment by conor-f** [comment]
Hey @githubsteve7

Thanks for the bug report. I have pushed a hotfix in 0.3.12 so you should be able to install now with no issues.

You can close this issue if all is working, and if not, I can help debug the install process further.

**Comment by githubsteve7** [comment]
The hotfix worked and I was able to install it, but the buttons are not reacting to mouse clicks. I'm using the flathub Spotify app if that makes a difference and on Fedora. Also currently playing is not showing. Thanks.

**Comment by conor-f** [comment]
Sorry for the late reply - Can you show me your polybar config please? 

Can you also verify that your `spotibar` config is correct by running `spotibar --auth` in a terminal? The output should say `Successfully authenticated.`.

**Comment by githubsteve7** [comment]
I ran spotibar --auth again and it's working. Thanks for help.
